"""change product model len

Revision ID: 43a1e8923fbc
Revises: 0d61d1e6551e
Create Date: 2022-11-03 15:15:11.800841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a1e8923fbc'
down_revision = '0d61d1e6551e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'gender',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=13),
               existing_nullable=True)
    op.alter_column('product', 'size',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=15),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'size',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('product', 'gender',
               existing_type=sa.String(length=13),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)
    # ### end Alembic commands ###
