"""class product and category fix v3

Revision ID: 570015392397
Revises: 30eb2797c2ae
Create Date: 2022-09-26 22:43:05.237747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570015392397'
down_revision = '30eb2797c2ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('phone_number', sa.String(length=12), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('shipping_adress', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=475), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('photos_path', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand_name', sa.String(length=40), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=7), nullable=True),
    sa.Column('size', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['categories.name'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=True)
    op.drop_index('ix_all_users_role', table_name='all_users')
    op.drop_table('all_users')
    op.drop_index('ix_products_name', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('name', sa.VARCHAR(length=475), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('photos_path', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('brand_name', sa.VARCHAR(length=40), nullable=True),
    sa.Column('color', sa.VARCHAR(length=20), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=7), nullable=True),
    sa.Column('size', sa.VARCHAR(length=10), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['categories.name'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_name', 'products', ['name'], unique=False)
    op.create_table('all_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=60), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=12), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('shipping_adress', sa.VARCHAR(length=200), nullable=True),
    sa.Column('password', sa.VARCHAR(length=128), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index('ix_all_users_role', 'all_users', ['role'], unique=False)
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
