"""model category fix

Revision ID: 7cd30883e181
Revises: cb88118a4d26
Create Date: 2022-10-13 14:50:56.883210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd30883e181'
down_revision = 'cb88118a4d26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('lft', sa.Integer(), nullable=False),
    sa.Column('rgt', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('category_level_idx', 'category', ['level'], unique=False)
    op.create_index('category_lft_idx', 'category', ['lft'], unique=False)
    op.create_index('category_rgt_idx', 'category', ['rgt'], unique=False)
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    op.drop_index('categories_level_idx', table_name='categories')
    op.drop_index('categories_lft_idx', table_name='categories')
    op.drop_index('categories_rgt_idx', table_name='categories')
    op.drop_index('ix_categories_name', table_name='categories')
    op.drop_table('categories')
    op.drop_table('shopping_cart')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'categories', ['category_id'], ['id'])
    op.create_table('shopping_cart',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('lft', sa.INTEGER(), nullable=False),
    sa.Column('rgt', sa.INTEGER(), nullable=False),
    sa.Column('level', sa.INTEGER(), nullable=False),
    sa.Column('tree_id', sa.INTEGER(), nullable=True),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_categories_name', 'categories', ['name'], unique=False)
    op.create_index('categories_rgt_idx', 'categories', ['rgt'], unique=False)
    op.create_index('categories_lft_idx', 'categories', ['lft'], unique=False)
    op.create_index('categories_level_idx', 'categories', ['level'], unique=False)
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_index('category_rgt_idx', table_name='category')
    op.drop_index('category_lft_idx', table_name='category')
    op.drop_index('category_level_idx', table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
