"""Add table Photo

Revision ID: 96e083a73809
Revises: cb88118a4d26
Create Date: 2022-10-11 01:30:25.172027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e083a73809'
down_revision = 'cb88118a4d26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('photos_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('products', 'photos_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('photos_path', sa.VARCHAR(), nullable=False))
    op.drop_table('photo')
    # ### end Alembic commands ###
