"""class fix

Revision ID: f1f19702cf5b
Revises: 570015392397
Create Date: 2022-09-28 14:36:47.568747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1f19702cf5b'
down_revision = '570015392397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category_id_number', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('category_name', sa.String(length=50), nullable=True))
    op.add_column('product', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'categories', ['category_name'], ['name'])
    op.create_foreign_key(None, 'product', 'categories', ['category_id_number'], ['id'])
    op.create_foreign_key(None, 'product', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('product', 'category_id')
    op.drop_column('product', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category', sa.VARCHAR(length=50), nullable=True))
    op.add_column('product', sa.Column('category_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'categories', ['category'], ['name'])
    op.create_foreign_key(None, 'product', 'categories', ['category_id'], ['id'])
    op.drop_column('product', 'user_id')
    op.drop_column('product', 'category_name')
    op.drop_column('product', 'category_id_number')
    # ### end Alembic commands ###
